exclude:
  - Gemfile

remote_theme: marella/jekyll-theme-documentation

title: WengerChan's Notes
toc_min: 2
toc_max: 3
owner_name: WengerChan
owner_url: https://github.com/WengerChan/notes

permalink: pretty
nav:
  - Getting Started:
    - About: ''
  - Docs:
    - Ansible: docs/Ansible
    - awk: docs/awk
    - Bonding: docs/Bonding
    - Emoji: docs/Emoji
    - Fedora-使用手册: docs/Fedora-使用手册
    - Git: docs/Git
    - Kvm: docs/Kvm
    - Linux: docs/Linux
    - LVM: docs/LVM
    - Markdown: docs/Markdown
    - Netcat: docs/Netcat
    - Netfilter/iptables: docs/Netfilter-iptables
    - NFS: docs/NFS
    - NTP: docs/NTP
    - RHCS: docs/RHCS
    - RPM: docs/RPM
    - Shell-圣经: docs/Shell-圣经-CN
    - Shell: docs/Shell
    - SSH: docs/SSH
    - Team: docs/Team
    - top: docs/top
    - vlmcsd: docs/vlmcsd
    - VSFTPD: docs/VSFTPD
    - 双网卡路由: docs/双网卡路由
    - 正则表达式: docs/正则表达式
    - 证书: docs/证书
    - 其他: docs/其他
  - Drafts:
    - DNS: draft/DNS
    - echo,printf: drafts/echo_printf
    - Git: drafts/Git
    - MySQL: drafts/MySQL
    - quota: drafts/quota
    - sed: drafts/sed
    - Systemd: draft/Systemd
    - Ubuntu: drafts/Ubuntu
    - 计算机网络: drafts/计算机网络
    - 三次握手与四次挥手: drafts/三次握手与四次挥手
    - 特殊字符: drafts/特殊字符
    - 左右mongodb右手redis读书笔记: drafts/左右mongodb右手redis读书笔记
  - Scripts:
    - Script-Lib: scripts/List

